export const PROFILE_STEPS = [
  {
    kicker: '01 — The substance',
    title: 'What are we working against?',
    hint: 'Pick every one that applies.',
    key: 'subs',
    note: "If you don't find yours, choose Other. More substances and instruments tailored to them will be added soon.",
    options: ['Alcohol', 'Opioids (Heroin, Fentanyl)', 'Stimulants (Meth, Cocaine)', 'Benzos (Xanax, Valium)', 'Nicotine', 'Other'],
  },
  {
    kicker: '02 — The trigger',
    title: 'What sets it off?',
    hint: 'Pick the ones that show up most.',
    key: 'triggers',
    options: ['Hunger', 'Anger', 'Loneliness', 'Tiredness', 'Boredom', 'Wanting a reward', 'Sexual arousal', 'Easy money', 'Environment cues', 'Physical pain', 'Withdrawal'],
  },
  {
    kicker: '03 — What works for you',
    title: 'What has actually worked before?',
    hint: 'Even once counts.',
    key: 'worked',
    options: ['Calling someone', 'Getting outside', 'Cold water', 'Waiting it out', 'Writing it down', 'Nothing yet'],
  },
  {
    kicker: '04 — Never suggest this',
    title: 'What should the app never hand you?',
    hint: 'This is a hard filter. It will be obeyed.',
    key: 'ruledOut',
    options: ['Religious or spirituality talk', 'Anything over ten minutes', 'Talking to a person', 'Outdoor or sport activities', 'Tough love', 'Nothing — try me!'],
  },
  {
    kicker: '05 — Medication and health',
    title: 'What are you on, and what are you dealing with?',
    hint: 'This tells us which techniques are safe for you.',
    key: 'treatment',
    options: ['Suboxone or methadone', 'Naltrexone', 'Antidepressants', 'In therapy', 'Anxiety treatment', 'ADHD', 'Trauma', 'Insomnia'],
  },
];

export const QUESTIONS = [
  {
    key: 'place',
    title: 'Where are you right now?',
    options: [
      { label: 'Home alone', sub: '' },
      { label: 'Home with other people', sub: '' },
      { label: 'Out in public', sub: '' },
      { label: 'At work', sub: '' },
      { label: 'Outdoors alone', sub: '' },
      { label: 'Somewhere I used to use', sub: '' },
      { label: 'Other', sub: '' },
    ],
  },
  {
    key: 'mag',
    title: 'How loud is it?',
    options: [
      { label: '1–3', sub: 'background noise' },
      { label: '4–6', sub: 'distracting' },
      { label: '7–8', sub: 'hard to think' },
      { label: '9–10', sub: 'madness' },
    ],
  },
  {
    key: 'emotion',
    title: 'Which emotion is strongest right now?',
    options: [
      { label: 'Anxiety', sub: '' },
      { label: 'Anger', sub: '' },
      { label: 'Shame', sub: '' },
      { label: 'Emptiness', sub: '' },
      { label: 'Grief', sub: '' },
      { label: 'Boredom', sub: '' },
      { label: 'Anticipation', sub: '' },
      { label: 'Loneliness', sub: '' },
      { label: 'Guilt', sub: '' },
      { label: 'Fear', sub: '' },
      { label: 'Restlessness', sub: '' },
    ],
  },
  {
    key: 'body',
    title: 'How does your body feel right now?',
    options: [
      { label: 'Wired', sub: '' },
      { label: 'Shaky or sick', sub: '' },
      { label: 'Numb', sub: '' },
      { label: 'Exhausted', sub: '' },
      { label: 'Tense', sub: '' },
      { label: 'In pain', sub: '' },
      { label: 'Nauseous', sub: '' },
      { label: 'Sweating', sub: '' },
      { label: 'Heart racing', sub: '' },
      { label: 'Normal', sub: '' },
    ],
  },
  {
    key: 'time',
    title: 'How long have you got?',
    options: [
      { label: 'Two minutes', sub: '' },
      { label: 'Five minutes', sub: '' },
      { label: 'Ten minutes', sub: '' },
      { label: 'Thirty minutes', sub: '' },
      { label: 'As long as it takes', sub: '' },
    ],
  },
];

export const INSTRUMENTS = [
  {
    id: 'tipp',
    triggerTags: ['Withdrawal', 'Physical pain'],
    worksForKey: 'Cold water',
    substanceRelevance: [],
    originOrg: 'Marsha Linehan / DBT Skills Training Manual',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Cold Water, Then One Breath',
    framework: 'Dialectical Behaviour Therapy — TIPP (distress tolerance)',
    frameworkNote:
      "Temperature, Intense exercise, Paced breathing, Paired muscle relaxation. Marsha Linehan's crash protocol for when the emotional system is past reasoning with.",
    why: 'At a 9 you cannot be talked out of anything, so this doesn\'t try. Cold on the face triggers the mammalian dive reflex and drops your heart rate inside sixty seconds. It buys the ninety seconds where a decision becomes possible again.',
    does: 'Physically interrupts the surge. It does not resolve anything, and it is not supposed to.',
    duration: '90 seconds',
    steps: [
      { t: 30, label: 'Cold water on your face', body: 'Sink, bottle, ice, snow. Face and the back of your neck. Hold it there while you count thirty.' },
      { t: 20, label: 'Breathe out longer than you breathe in', body: 'In for four. Out for eight. The long exhale is the part that works.' },
      { t: 40, label: 'Sit down and say the time out loud', body: 'Name the hour and where you are. You are coming back into the room.' },
    ],
    tags: {
      mag: ['9–10', '7–8'],
      time: ['Two minutes', 'Five minutes'],
      body: ['Wired', 'Shaky or sick', 'Heart racing', 'Sweating', 'Tense'],
      place: ['Home alone', 'Outdoors alone', 'Out in public', 'At work'],
    },
  },
  {
    id: 'surf',
    triggerTags: ['Boredom', 'Wanting a reward'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Alan Marlatt & Sarah Bowen / Mindfulness-Based Relapse Prevention',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Urge Surfing',
    framework: 'Mindfulness-Based Relapse Prevention',
    frameworkNote:
      "Alan Marlatt's core technique. The urge is treated as a wave with a peak and a decline rather than a command; you time it instead of fighting it.",
    why: 'Cravings have a shape. Yours peaks and falls in about twenty minutes whether or not you act on it. This makes the falling part visible so the peak stops feeling permanent.',
    does: 'Turns an emergency into a weather event you are watching from the shore.',
    duration: '6 minutes',
    steps: [
      { t: 60, label: 'Find where it lives in your body', body: "Chest, jaw, stomach, hands. Don't describe it as wanting. Describe it as pressure, temperature, weight." },
      { t: 90, label: 'Rate it, then wait', body: "Give it a number out of ten. Keep watching the same spot. Don't argue with it." },
      { t: 90, label: 'Rate it again', body: 'Higher, lower, moved somewhere else? Whatever it did, it did without you doing anything.' },
      { t: 120, label: 'Ride it down', body: 'Stay with it until the number drops by two. It will. That is the whole trick.' },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Ten minutes', 'Thirty minutes'],
      emotion: ['Anxiety', 'Anticipation', 'Boredom', 'Restlessness'],
      place: ['Home alone', 'Home with other people'],
    },
  },
  {
    id: 'tape',
    triggerTags: ['Wanting a reward', 'Easy money'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Standard CBT relapse-prevention (decisional balance)',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Play The Tape Forward',
    framework: 'Cognitive Behavioural Therapy — decisional balance',
    frameworkNote:
      'Standard cognitive-behavioural relapse prevention: the craving only shows you the first frame, so you deliberately run the reel to the end.',
    why: 'It feels good right now — that is why this one is dangerous. The craving is showing you the first ten minutes and hiding the next fourteen hours. You are going to watch the whole thing.',
    does: 'Restores the missing consequences so the decision is made on complete information.',
    duration: '4 minutes',
    steps: [
      { t: 45, label: 'First ten minutes. Say it out loud', body: "Exactly what you'd get. Don't sanitise it — the relief is real and pretending otherwise breaks the exercise." },
      { t: 45, label: 'Hour three', body: 'Where are you, who have you texted, what is the count at?' },
      { t: 60, label: 'Tomorrow, 7am', body: 'First thought on waking. Who you have to look at. What you have to redo.' },
      { t: 60, label: 'Now the other reel', body: 'Same 7am, if you don\'t. Nothing dramatic. Just ordinary and intact.' },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Five minutes', 'Ten minutes'],
      emotion: ['Anticipation', 'Boredom', 'Emptiness', 'Guilt'],
      place: ['Somewhere I used to use', 'Home alone'],
    },
  },
  {
    id: 'leave',
    triggerTags: ['Environment cues'],
    worksForKey: 'Getting outside',
    substanceRelevance: [],
    originOrg: 'Behavioural stimulus-control literature (cue exposure)',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Leave The Room',
    framework: 'Stimulus control — behavioural',
    frameworkNote: 'Cue exposure is the strongest single predictor of use. The cheapest intervention available is distance, applied immediately.',
    why: 'You are standing in the place. No technique out-argues a cue this loud — everything else works better from two hundred metres away. Move first, think second.',
    does: 'Removes the trigger instead of managing it.',
    duration: '3 minutes',
    steps: [
      { t: 20, label: 'Stand up. Now', body: 'Before the next sentence. Coat, phone, door.' },
      { t: 60, label: 'Two hundred metres, any direction', body: 'Uphill if there is an uphill. Count the paces.' },
      { t: 60, label: 'Text one person that you left', body: "Three words is enough. It makes going back a decision you'd have to explain." },
    ],
    tags: {
      mag: ['7–8', '9–10'],
      time: ['Two minutes', 'Five minutes', 'Ten minutes'],
      place: ['Somewhere I used to use', 'Out in public'],
    },
  },
  {
    id: 'ground',
    triggerTags: ['Physical pain', 'Withdrawal'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Trauma-informed grounding practice',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: '5–4–3–2–1',
    framework: 'Trauma-informed grounding',
    frameworkNote: 'Sensory orienting. Used to bring attention out of an internal loop and back into the present environment, silently and in public.',
    why: "You're in public and shaking. This one is invisible — nobody standing next to you will know you are doing it, and it works on anxiety faster than it works on craving.",
    does: 'Pulls attention out of your head and into the room.',
    duration: '3 minutes',
    steps: [
      { t: 45, label: 'Five things you can see', body: 'Small and specific. A scuff, a bolt, a price tag.' },
      { t: 40, label: 'Four you can feel', body: 'Fabric at your wrist, floor through your shoes, air on your face.' },
      { t: 35, label: 'Three you can hear', body: 'Nearest, then furthest.' },
      { t: 30, label: 'Two you can smell, one you can taste', body: 'Then breathe out slowly and look up.' },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Two minutes', 'Five minutes'],
      place: ['Out in public', 'At work'],
      emotion: ['Anxiety', 'Shame', 'Fear'],
      body: ['Wired', 'Shaky or sick', 'Nauseous', 'Tense'],
    },
  },
  {
    id: 'delay',
    triggerTags: ['Boredom', 'Wanting a reward', 'Easy money'],
    worksForKey: 'Waiting it out',
    substanceRelevance: [],
    originOrg: 'SMART Recovery (DEADS)',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'The Fifteen-Minute Deal',
    framework: 'SMART Recovery — Deny, Escape, Avoid, Distract, Substitute',
    frameworkNote: 'Deny, Escape, Avoid, Distract, Substitute. You are not promising never; you are promising not yet, for a period short enough to be honest.',
    why: 'You never agreed to quit tonight. You agreed to fifteen minutes, which is a promise you can actually keep, and cravings rarely survive being made to wait with something in your hands.',
    does: "Converts an absolute into a delay you won't have to lie about.",
    duration: '15 minutes',
    steps: [
      { t: 30, label: 'Set fifteen minutes. Say the deal out loud', body: '"Not before this runs out." That\'s the whole contract.' },
      { t: 60, label: 'Put something in your hands', body: 'Food, shower, dishes, cigarette, cold drink. Hands busy, ideally wet or cold.' },
      { t: 90, label: 'When it runs out, re-rate it', body: 'If it dropped, take another fifteen. If it didn\'t, we change instrument.' },
    ],
    tags: {
      mag: ['4–6', '1–3'],
      time: ['Thirty minutes', 'As long as it takes'],
      emotion: ['Boredom', 'Emptiness'],
      body: ['Numb', 'Exhausted', 'In pain'],
    },
  },
  {
    id: 'call',
    triggerTags: ['Loneliness'],
    worksForKey: 'Calling someone',
    substanceRelevance: [],
    originOrg: 'Peer-support / twelve-step-adjacent social support literature',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'One Call, Script Written',
    framework: 'Social support — twelve-step adjacent',
    frameworkNote: 'The reach-out, stripped of fellowship language. What carries over from AA and NA is only this: the odds change when someone else knows in real time.',
    why: "The reason this fails is never willingness, it's not knowing what to open with — so the opening line is written for you and you only have to press call.",
    does: 'Puts a second person inside the next hour.',
    duration: '5 minutes',
    steps: [
      { t: 20, label: 'Read the line', body: '"It\'s bad tonight and I\'m not asking you to fix it. Just stay on the phone."' },
      { t: 30, label: 'Press call before you edit it', body: 'Editing is how this gets abandoned.' },
      { t: 120, label: 'Say where you are', body: "Location first, feelings second. It's the part that matters if this goes wrong." },
    ],
    tags: {
      mag: ['7–8', '9–10'],
      time: ['Ten minutes', 'Thirty minutes', 'As long as it takes'],
      emotion: ['Shame', 'Grief', 'Emptiness', 'Loneliness'],
      place: ['Home alone', 'Outdoors alone'],
    },
  },
  {
    id: 'night',
    triggerTags: ['Tiredness'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Behavioural sleep-as-endpoint literature',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Cut The Night Short',
    framework: 'Behavioural — sleep as endpoint',
    frameworkNote: 'Late-night relapse is overwhelmingly a function of hours awake and alone. Ending the day early is a legitimate intervention, not a retreat.',
    why: "You're exhausted with the whole night ahead of you and no reason to still be awake. Nothing good is coming at 2am. Ending the day is a win, not a surrender.",
    does: 'Closes the window rather than defending it.',
    duration: '20 minutes',
    steps: [
      { t: 60, label: 'Phone on the far side of the room', body: 'Charging, screen down, out of arm\'s reach.' },
      { t: 90, label: 'Shower as hot as you can stand', body: 'Then let yourself get cold. The temperature drop is what makes you sleepy.' },
      { t: 120, label: 'Bed, lights off, something spoken', body: "Podcast or audiobook, volume low, timer on. Something you've heard before." },
    ],
    tags: {
      mag: ['1–3', '4–6'],
      time: ['Thirty minutes', 'As long as it takes'],
      body: ['Exhausted', 'Numb'],
      place: ['Home alone', 'Outdoors alone'],
    },
  },
  {
    id: 'stop',
    triggerTags: ['Wanting a reward', 'Easy money', 'Sexual arousal'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Marsha Linehan / DBT Skills Training Manual',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Stop. Then Decide',
    framework: 'Dialectical Behaviour Therapy — STOP skill',
    frameworkNote:
      'One of DBT\'s four core distress-tolerance skills: Stop, Take a step back, Observe, Proceed mindfully. Built for the exact moment an urge turns into motion.',
    why: 'The urge to act is fastest right when it starts. This doesn\'t try to talk you out of it — it puts four short steps between the impulse and your hands, which is often enough for the next choice to stop being automatic.',
    does: 'Interrupts the impulse-to-action chain before it becomes a decision.',
    duration: '90 seconds',
    steps: [
      { t: 15, label: 'Stop. Freeze exactly where you are', body: "Don't take even a small step toward it yet. Just stop moving toward it." },
      { t: 20, label: 'Take a step back', body: 'Physically or mentally. One breath. Let go of the pressure to react this second.' },
      { t: 30, label: "Observe what's actually happening", body: 'What are you thinking, feeling, and what\'s around you — inside and outside.' },
      { t: 25, label: 'Proceed mindfully', body: 'Ask what response fits what you actually want, not just the urge. Choose one small next action.' },
    ],
    tags: {
      mag: ['7–8', '9–10'],
      time: ['Two minutes'],
      body: ['Wired', 'Heart racing'],
      place: ['Home alone', 'Out in public', 'At work', 'Outdoors alone'],
    },
  },
  {
    id: 'accepts',
    triggerTags: ['Boredom', 'Tiredness'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Marsha Linehan / DBT Skills Training Manual',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'The Distraction List',
    framework: 'Dialectical Behaviour Therapy — ACCEPTS (distraction)',
    frameworkNote:
      'ACCEPTS — Activities, Contributing, Comparisons, Emotions (opposite ones), Pushing away, Thoughts, Sensations. A DBT distress-tolerance skill for urges that are strong but not yet an emergency.',
    why: "When the craving is loud but not a full physiological flood, out-arguing it rarely works — out-occupying it does. This gives your attention somewhere else to go that isn't willpower.",
    does: 'Occupies the same channel the craving is using, on purpose, until the urge loses its grip.',
    duration: '4 minutes',
    steps: [
      { t: 40, label: 'Pick one thing, not five', body: 'Activities, contributing, comparisons, emotions, pushing away, thoughts, sensations — pick one lane and commit to it.' },
      { t: 90, label: 'Do it with your hands or your body', body: 'Clean something, text a friend, watch something that makes you laugh, hold ice, count backward from 100 by 7s.' },
      { t: 110, label: "Keep going until the edge is off", body: "You're not solving anything. You're occupying the part of your brain that's currently running the show." },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Five minutes', 'Ten minutes'],
      emotion: ['Boredom', 'Restlessness'],
      place: ['Home alone', 'Home with other people', 'At work'],
    },
  },
  {
    id: 'soothe',
    triggerTags: ['Boredom', 'Loneliness'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Marsha Linehan / DBT Skills Training Manual',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Something For Every Sense',
    framework: 'Dialectical Behaviour Therapy — Self-Soothe',
    frameworkNote:
      "A DBT distress-tolerance skill: deliberately feeding each of the five senses something real, one at a time, instead of leaving the craving as the only thing broadcasting.",
    why: "Numbness and emptiness don't respond well to arguments — they respond to input. This gives every sense something ordinary and real on purpose.",
    does: 'Replaces sensory numbness with deliberate, ordinary sensation.',
    duration: '5 minutes',
    steps: [
      { t: 75, label: 'Sight and sound', body: "Put on something that isn't background noise — actually look at or listen to it. A window, a photo, one song end to end." },
      { t: 75, label: 'Touch and smell', body: 'Something warm or textured in your hands. Coffee, a candle, lotion, fresh air if you can get to it.' },
      { t: 75, label: 'Taste, last', body: "Something you'd actually enjoy, slowly. Not a reward for anything — just proof your senses still work for things that aren't the craving." },
      { t: 75, label: 'Notice what changed', body: "Not gone — just quieter. That's the whole point of this one." },
    ],
    tags: {
      mag: ['4–6'],
      time: ['Five minutes', 'Ten minutes'],
      emotion: ['Emptiness', 'Boredom'],
      body: ['Numb', 'Exhausted'],
      place: ['Home alone', 'Home with other people'],
    },
  },
  {
    id: 'accept',
    triggerTags: ['Physical pain'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Marsha Linehan / DBT Skills Training Manual',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: "This Is What's True Right Now",
    framework: 'Dialectical Behaviour Therapy — Radical Acceptance',
    frameworkNote:
      "A DBT distress-tolerance skill for pain that's fused to a fact you can't change tonight. Accepting isn't approving — it's ending the extra fight on top of the fact.",
    why: "Some cravings are fused to a fact you can't change tonight — a loss, a diagnosis, a relationship that's over. Fighting the fact keeps the craving fed. This doesn't ask you to be at peace with it, only to stop spending the fight on the wrong target.",
    does: "Separates the pain that's unavoidable from the extra suffering that comes from refusing what's already true.",
    duration: '6 minutes',
    steps: [
      { t: 60, label: "Say the fact, not the story", body: "Name what's actually true right now, in one plain sentence. Not what it means, not what happens next — just the fact." },
      { t: 90, label: "Notice what you're fighting", body: "Most of what hurts right now is the arguing-with-reality part, not the reality itself. Let the arguing go slack for a minute." },
      { t: 90, label: 'Accept it without agreeing with it', body: "Accepting isn't approving. You can hate that it's true and still stop spending energy pretending it isn't." },
      { t: 120, label: "Ask what's next, given that", body: "Not what you wish were true. Given the actual fact, what's one thing you can do in the next ten minutes?" },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Ten minutes', 'Thirty minutes'],
      emotion: ['Grief', 'Anger', 'Shame'],
    },
  },
  {
    id: 'cba',
    triggerTags: ['Wanting a reward', 'Boredom'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'SMART Recovery',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'The Two-Column Truth',
    framework: 'SMART Recovery — Cost-Benefit Analysis',
    frameworkNote:
      "A core SMART Recovery tool: write down what you get and what it costs, side by side, before you decide instead of after. Not a lecture — just the two columns you're currently only looking at one of.",
    why: "Right now you're only running the benefit column in your head — the relief, the quiet, the reward. This makes you write the cost column too, in your own words, before you act instead of at 3am after.",
    does: 'Forces both sides of the decision onto the page at the same time, instead of one side in your head and the other in hindsight.',
    duration: '5 minutes',
    steps: [
      { t: 75, label: 'Short-term benefit, in your own words', body: 'What do you actually get in the next hour if you do this? Be honest, not virtuous. The relief is real.' },
      { t: 90, label: 'Cost, in your own words', body: 'What does it cost you tomorrow, this week, this year? Specific, not vague. Not "it\'s bad for me" — what actually happens.' },
      { t: 135, label: 'Put them side by side', body: "Read both columns out loud, one after the other. You're not choosing yet — you're just finally looking at the whole page." },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Five minutes', 'Ten minutes'],
      emotion: ['Anticipation', 'Boredom'],
    },
  },
  {
    id: 'abc',
    triggerTags: ['Anger', 'Hunger'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'SMART Recovery (adapted from REBT / Albert Ellis)',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Trace It Back',
    framework: 'SMART Recovery — ABC (Activator, Belief, Consequence)',
    frameworkNote:
      "SMART Recovery's ABC tool, adapted from REBT. The activating event isn't what's driving this — the belief about it is, and that's the part you can actually catch.",
    why: "It feels like the event caused this — but the event happened to everyone in the room and only you are standing here. It's the belief in between that's doing the damage, and beliefs are the one part of this you can actually catch and question.",
    does: 'Separates what happened from what you told yourself it meant, so you can argue with the second one.',
    duration: '6 minutes',
    steps: [
      { t: 60, label: 'Name the activator', body: 'What actually happened, in one plain sentence. Not the meaning — just the event.' },
      { t: 90, label: 'Name the belief', body: 'What did you tell yourself it meant about you? Finish the sentence: "This means I..."' },
      { t: 90, label: 'Name the consequence', body: 'What did that belief make you feel, and what is it telling you to do right now?' },
      { t: 120, label: 'Question the belief, not the event', body: 'Is the belief actually true, or just familiar? What would you tell someone else who said it about themselves?' },
    ],
    tags: {
      emotion: ['Anger', 'Shame', 'Guilt'],
      mag: ['4–6', '7–8'],
      time: ['Ten minutes'],
    },
  },
  {
    id: 'sober',
    triggerTags: ['Tiredness', 'Environment cues'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Sarah Bowen / Mindfulness-Based Relapse Prevention',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'The SOBER Space',
    framework: 'Mindfulness-Based Relapse Prevention — SOBER breathing space',
    frameworkNote:
      "Stop, Observe, Breathe, Expand, Respond. MBRP's short-form reset for exactly the moment things start moving too fast to think.",
    why: "You don't have twenty minutes right now and you don't need them — this is the version that fits into a bathroom stall or a parking lot. Five steps, all of them short.",
    does: 'Interrupts the automatic-pilot chain in under three minutes, in a way nobody around you can tell you\'re doing.',
    duration: '3 minutes',
    steps: [
      { t: 20, label: 'Stop', body: "Whatever you're doing, pause it. Don't finish the motion." },
      { t: 25, label: 'Observe', body: "What's happening right now — in your body, your thoughts, around you. Just notice, don't fix." },
      { t: 40, label: 'Breathe', body: 'One breath, all the way down to your stomach. Just the one.' },
      { t: 45, label: 'Expand', body: 'Widen out from the breath to your whole body, then the room you\'re in.' },
      { t: 50, label: 'Respond', body: 'Now choose the next thing on purpose, instead of on autopilot.' },
    ],
    tags: {
      place: ['At work', 'Out in public'],
      mag: ['4–6', '7–8'],
      time: ['Two minutes', 'Five minutes'],
    },
  },
  {
    id: 'scan',
    triggerTags: ['Tiredness', 'Physical pain'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Sarah Bowen / Mindfulness-Based Relapse Prevention',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Three Minutes, Head To Toe',
    framework: 'Mindfulness-Based Relapse Prevention — Body Scan',
    frameworkNote:
      "A shortened MBRP body scan. Used when the craving has gone quiet in your head but is still running in your body — numbness, tension, exhaustion that a thought-focused technique won't reach.",
    why: "Some of this isn't in your head right now — it's in your shoulders, your jaw, your stomach. This finds where it's actually sitting instead of arguing with a thought that isn't the real problem.",
    does: "Locates the craving in the body instead of trying to think your way out of something that isn't happening in your thoughts.",
    duration: '4 minutes',
    steps: [
      { t: 60, label: 'Feet and legs', body: "What's actually there — heavy, tense, nothing at all. Don't change it, just find it." },
      { t: 60, label: 'Stomach and chest', body: "This is usually where it's loudest. Notice it without tightening against it." },
      { t: 60, label: 'Shoulders, jaw, hands', body: 'Where you hold things without noticing. Let them be exactly as tense as they are.' },
      { t: 60, label: 'The whole body, at once', body: 'Everything you just found, together. Breathe into the parts that are still loud.' },
    ],
    tags: {
      body: ['Numb', 'Tense', 'Exhausted'],
      place: ['Home alone', 'Home with other people'],
      time: ['Five minutes', 'Ten minutes'],
    },
  },
  {
    id: 'catch',
    triggerTags: ['Anger', 'Loneliness'],
    worksForKey: 'Writing it down',
    substanceRelevance: [],
    originOrg: 'Standard CBT thought-record practice',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Catch The Thought',
    framework: 'Cognitive Behavioural Therapy — Thought Record',
    frameworkNote:
      'Standard CBT thought-record work: get the automatic thought onto paper where it can be checked, instead of leaving it running unexamined in your head.',
    why: 'The thought driving this — "I can\'t handle this," "everyone does this," "just this once" — sounds true because it\'s fast and it\'s yours. Slow it down onto paper and it usually loses some of its authority.',
    does: "Turns an automatic thought into something you wrote down and can argue with, instead of something that just happened to you.",
    duration: '5 minutes',
    steps: [
      { t: 45, label: 'Write the thought, word for word', body: "Exactly what's going through your head, not the cleaned-up version." },
      { t: 60, label: 'Write the evidence for it', body: 'What actually supports this being true, right now, specifically.' },
      { t: 60, label: 'Write the evidence against it', body: 'What you know that contradicts it. Be as thorough as you were in the last step.' },
      { t: 135, label: 'Write a truer thought', body: "Not a forced positive one — one that actually fits the evidence better than the first one did." },
    ],
    tags: {
      emotion: ['Shame', 'Guilt', 'Fear'],
      time: ['Five minutes', 'Ten minutes'],
      mag: ['4–6'],
    },
  },
  {
    id: 'ifthen',
    triggerTags: ['Environment cues', 'Easy money'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Standard CBT practice (implementation intentions)',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'If This, Then That',
    framework: 'Cognitive Behavioural Therapy — Implementation Intentions',
    frameworkNote:
      "Implementation intentions: pre-deciding a specific response to a specific trigger, so the moment it happens doesn't require a fresh decision under pressure.",
    why: "You're standing in the exact situation you're worst at deciding in. This isn't asking you to decide right now — it's asking you to write down the decision so future-you doesn't have to make it from scratch.",
    does: "Replaces an in-the-moment decision with one you already made when you had more room to think.",
    duration: '3 minutes',
    steps: [
      { t: 40, label: 'Name the exact trigger', body: 'Not the general pattern — the specific thing in front of you right now.' },
      { t: 60, label: 'Write the if-then, out loud', body: '"If [this happens], then I will [specific action]." One sentence. Say it like a rule, not a hope.' },
      { t: 80, label: 'Do the "then" part now', body: "Not later. The whole plan is worthless if it waits until you feel like it." },
    ],
    tags: {
      place: ['Out in public', 'At work'],
      time: ['Two minutes', 'Five minutes'],
      mag: ['4–6', '7–8'],
    },
  },
  {
    id: 'defuse',
    triggerTags: ['Wanting a reward', 'Sexual arousal'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Acceptance and Commitment Therapy practice',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Just A Thought, Passing By',
    framework: 'Acceptance and Commitment Therapy — Cognitive Defusion',
    frameworkNote:
      'ACT\'s core defusion move: change your relationship to the thought instead of trying to win an argument with it. "I need this" becomes a thing your mind is saying, not an order.',
    why: 'You\'re not going to out-argue "I need this" — it doesn\'t respond to logic because it isn\'t a logical claim, it\'s a craving wearing a sentence. This doesn\'t fight it. It just relabels what it actually is.',
    does: 'Puts distance between you and the thought without requiring you to believe the thought is false.',
    duration: '4 minutes',
    steps: [
      { t: 40, label: 'Name the thought exactly', body: 'Not "I\'m craving" — the actual sentence. "I need this right now" or whatever it\'s saying.' },
      { t: 60, label: 'Add four words in front of it', body: '"I\'m having the thought that..." Say the whole sentence again with those four words stuck on the front.' },
      { t: 60, label: 'Say it in a stupid voice', body: "Cartoon voice, slow motion, whatever. Notice the thought didn't get weaker or stronger — just less like an order." },
      { t: 80, label: "Let it sit there, don't argue", body: "You don't have to make it leave. It can be in the room while you do something else." },
    ],
    tags: {
      emotion: ['Anticipation', 'Anxiety'],
      mag: ['4–6', '7–8'],
      time: ['Five minutes'],
    },
  },
  {
    id: 'values',
    triggerTags: ['Boredom', 'Loneliness'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Acceptance and Commitment Therapy practice',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'What This Actually Costs',
    framework: 'Acceptance and Commitment Therapy — Values Clarification',
    frameworkNote:
      "ACT values work: reconnecting with what you actually want your life to be about, as leverage instead of fear. Fear-based reasons wear out fast; this doesn't rely on being scared enough.",
    why: "Willpower fuelled by fear runs out — it's why \"rock bottom\" motivation never lasts on its own. This asks a different question: not what you're scared of, but who you're actually trying to be. That one holds up longer.",
    does: 'Replaces fear as the reason to stop with something that doesn\'t fade after the fear does.',
    duration: '6 minutes',
    steps: [
      { t: 60, label: "Name one person you don't want to let down", body: 'Not the general idea of disappointing people — one actual person.' },
      { t: 90, label: "Name what kind of person you're trying to be", body: "Not the person you're afraid of becoming — the one you're actually aiming at." },
      { t: 90, label: 'Ask if this gets you closer or further', body: 'Not whether it\'s "bad." Whether it moves you toward that person or away from them.' },
      { t: 120, label: 'Pick one thing that moves you toward it', body: 'Something small and doable in the next ten minutes.' },
    ],
    tags: {
      emotion: ['Emptiness', 'Grief'],
      time: ['Ten minutes', 'Thirty minutes'],
      mag: ['4–6'],
    },
  },
];

export const RULE_BLOCK = {
  'Talking to a person': ['call'],
  'Outdoor or sport activities': ['leave'],
  'Anything over ten minutes': ['delay', 'night', 'surf'],
};

export const HARM_ITEMS = [
  { label: "For opioids: make sure naloxone is at arm's length", sub: 'Not in a drawer. Not in a bag. Within sight.' },
  { label: 'Ensure someone is nearby and you are in reach of help', sub: 'Most overdoses are survivable with a witness.' },
  { label: 'Take nothing on top of it', sub: 'No benzos, no alcohol, no second thing.' },
  { label: 'Test it, then take a quarter first', sub: 'Tolerance is gone after a break. Wait ten minutes.' },
  { label: 'Stay hydrated and put something in your stomach', sub: "If it's alcohol: one glass of water between each." },
  { label: 'Make sure one person knows where you are', sub: "Give them the actual address, not just 'out tonight'." },
];
