export const PROFILE_STEPS = [
  {
    kicker: '01 — The substance',
    title: 'What are we working against?',
    hint: 'Pick every one that applies.',
    key: 'subs',
    note: "If you don't find yours, choose Other. More substances and instruments tailored to them will be added soon.",
    options: ['Alcohol', 'Opioids (Heroin, Fentanyl)', 'Stimulants (Meth, Cocaine)', 'Benzos (Xanax, Valium)', 'Nicotine', 'Other'],
  },
  {
    kicker: '02 — The trigger',
    title: 'What sets it off?',
    hint: 'Pick the ones that show up most.',
    key: 'triggers',
    options: ['Hunger', 'Anger', 'Loneliness', 'Tiredness', 'Boredom', 'Wanting a reward', 'Sexual arousal', 'Easy money', 'Environment cues', 'Physical pain', 'Withdrawal'],
  },
  {
    kicker: '03 — What works for you',
    title: 'What has actually worked before?',
    hint: 'Even once counts.',
    key: 'worked',
    options: [
      'Calling someone',
      'Getting outside',
      'Cold water',
      'Waiting it out',
      'Writing it down',
      'Distracting myself on purpose',
      "Reminding myself it'll pass",
      'Picturing how I\'d feel later',
      'Tensing and releasing my body',
      'Nothing yet',
    ],
  },
  {
    kicker: '04 — How you cope',
    title: 'When it\'s bad, what do you actually reach for?',
    hint: "Not what's worked — just what kind of thing you'd rather try.",
    key: 'style',
    options: [
      'Thinking it through',
      'Moving my body',
      'Reaching out to someone',
      'Getting distracted on purpose',
      'Sitting with it quietly',
      'Being blunt with myself',
    ],
  },
  {
    kicker: '05 — Never suggest this',
    title: 'What should the app never hand you?',
    hint: 'This is a hard filter. It will be obeyed.',
    key: 'ruledOut',
    options: ['Religious or spirituality talk', 'Philosophy or wisdom-tradition framing', 'Anything over ten minutes', 'Talking to a person', 'Outdoor or sport activities', 'Tough love', 'Nothing — try me!'],
  },
  {
    kicker: '06 — Medication and health',
    title: 'What are you on, and what are you dealing with?',
    hint: 'This tells us which techniques are safe for you.',
    key: 'treatment',
    options: ['Suboxone or methadone', 'Naltrexone', 'Antidepressants', 'In therapy', 'Anxiety treatment', 'ADHD', 'Trauma', 'Insomnia'],
  },
];

export const QUESTIONS = [
  {
    key: 'place',
    title: 'Where are you right now?',
    options: [
      { label: 'Home alone', sub: '' },
      { label: 'Home with other people', sub: '' },
      { label: 'Out in public', sub: '' },
      { label: 'At work', sub: '' },
      { label: 'Outdoors alone', sub: '' },
      { label: 'Somewhere I used to use', sub: '' },
      { label: 'Other', sub: '' },
    ],
  },
  {
    key: 'mag',
    title: 'How loud is it?',
    options: [
      { label: '1–3', sub: 'background noise' },
      { label: '4–6', sub: 'distracting' },
      { label: '7–8', sub: 'hard to think' },
      { label: '9–10', sub: 'madness' },
    ],
  },
  {
    key: 'emotion',
    title: 'Which emotion is strongest right now?',
    options: [
      { label: 'Anxiety', sub: '' },
      { label: 'Anger', sub: '' },
      { label: 'Shame', sub: '' },
      { label: 'Emptiness', sub: '' },
      { label: 'Grief', sub: '' },
      { label: 'Boredom', sub: '' },
      { label: 'Anticipation', sub: '' },
      { label: 'Loneliness', sub: '' },
      { label: 'Guilt', sub: '' },
      { label: 'Fear', sub: '' },
      { label: 'Restlessness', sub: '' },
    ],
  },
  {
    key: 'body',
    title: 'How does your body feel right now?',
    options: [
      { label: 'Wired', sub: '' },
      { label: 'Shaky or sick', sub: '' },
      { label: 'Numb', sub: '' },
      { label: 'Exhausted', sub: '' },
      { label: 'Tense', sub: '' },
      { label: 'In pain', sub: '' },
      { label: 'Nauseous', sub: '' },
      { label: 'Sweating', sub: '' },
      { label: 'Heart racing', sub: '' },
      { label: 'Normal', sub: '' },
    ],
  },
  {
    key: 'time',
    title: 'How long have you got?',
    options: [
      { label: 'Two minutes', sub: '' },
      { label: 'Five minutes', sub: '' },
      { label: 'Ten minutes', sub: '' },
      { label: 'Thirty minutes', sub: '' },
      { label: 'As long as it takes', sub: '' },
    ],
  },
];

export const INSTRUMENTS = [
  {
    id: 'tipp',
    triggerTags: ['Withdrawal', 'Physical pain'],
    styleTags: ['Moving my body'],
    worksForKey: 'Cold water',
    substanceRelevance: [],
    originOrg: 'Marsha Linehan / DBT Skills Training Manual',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Cold Water, Then One Breath',
    framework: 'Dialectical Behaviour Therapy — TIPP (distress tolerance)',
    frameworkNote:
      "Temperature, Intense exercise, Paced breathing, Paired muscle relaxation. Marsha Linehan's crash protocol for when the emotional system is past reasoning with.",
    why: 'At a 9 you cannot be talked out of anything, so this doesn\'t try. Cold on the face triggers the mammalian dive reflex and drops your heart rate inside sixty seconds. It buys the ninety seconds where a decision becomes possible again.',
    does: 'Physically interrupts the surge. It does not resolve anything, and it is not supposed to.',
    duration: '90 seconds',
    steps: [
      { t: 30, label: 'Cold water on your face', body: 'Sink, bottle, ice, snow. Face and the back of your neck. Hold it there while you count thirty.' },
      { t: 20, label: 'Breathe out longer than you breathe in', body: 'In for four. Out for eight. The long exhale is the part that works.' },
      { t: 40, label: 'Sit down and say the time out loud', body: 'Name the hour and where you are. You are coming back into the room.' },
    ],
    tags: {
      mag: ['9–10', '7–8'],
      time: ['Two minutes', 'Five minutes'],
      body: ['Wired', 'Shaky or sick', 'Heart racing', 'Sweating', 'Tense'],
      place: ['Home alone', 'Outdoors alone', 'Out in public', 'At work'],
    },
  },
  {
    id: 'surf',
    triggerTags: ['Boredom', 'Wanting a reward'],
    styleTags: ['Sitting with it quietly'],
    worksForKey: "Reminding myself it'll pass",
    substanceRelevance: [],
    originOrg: 'Alan Marlatt & Sarah Bowen / Mindfulness-Based Relapse Prevention',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Urge Surfing',
    framework: 'Mindfulness-Based Relapse Prevention',
    frameworkNote:
      "Alan Marlatt's core technique. The urge is treated as a wave with a peak and a decline rather than a command; you time it instead of fighting it.",
    why: 'Cravings have a shape. Yours peaks and falls in about twenty minutes whether or not you act on it. This makes the falling part visible so the peak stops feeling permanent.',
    does: 'Turns an emergency into a weather event you are watching from the shore.',
    duration: '6 minutes',
    steps: [
      { t: 60, label: 'Find where it lives in your body', body: "Chest, jaw, stomach, hands. Don't describe it as wanting. Describe it as pressure, temperature, weight." },
      { t: 90, label: 'Rate it, then wait', body: "Give it a number out of ten. Keep watching the same spot. Don't argue with it." },
      { t: 90, label: 'Rate it again', body: 'Higher, lower, moved somewhere else? Whatever it did, it did without you doing anything.' },
      { t: 120, label: 'Ride it down', body: 'Stay with it until the number drops by two. It will. That is the whole trick.' },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Ten minutes', 'Thirty minutes'],
      emotion: ['Anxiety', 'Anticipation', 'Boredom', 'Restlessness'],
      place: ['Home alone', 'Home with other people'],
    },
  },
  {
    id: 'tape',
    triggerTags: ['Wanting a reward', 'Easy money'],
    styleTags: ['Thinking it through'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Standard CBT relapse-prevention (decisional balance)',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Play The Tape Forward',
    framework: 'Cognitive Behavioural Therapy — decisional balance',
    frameworkNote:
      'Standard cognitive-behavioural relapse prevention: the craving only shows you the first frame, so you deliberately run the reel to the end.',
    why: 'It feels good right now — that is why this one is dangerous. The craving is showing you the first ten minutes and hiding the next fourteen hours. You are going to watch the whole thing.',
    does: 'Restores the missing consequences so the decision is made on complete information.',
    duration: '4 minutes',
    steps: [
      { t: 45, label: 'First ten minutes. Say it out loud', body: "Exactly what you'd get. Don't sanitise it — the relief is real and pretending otherwise breaks the exercise." },
      { t: 45, label: 'Hour three', body: 'Where are you, who have you texted, what is the count at?' },
      { t: 60, label: 'Tomorrow, 7am', body: 'First thought on waking. Who you have to look at. What you have to redo.' },
      { t: 60, label: 'Now the other reel', body: 'Same 7am, if you don\'t. Nothing dramatic. Just ordinary and intact.' },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Five minutes', 'Ten minutes'],
      emotion: ['Anticipation', 'Boredom', 'Emptiness', 'Guilt'],
      place: ['Somewhere I used to use', 'Home alone'],
    },
  },
  {
    id: 'leave',
    triggerTags: ['Environment cues'],
    styleTags: ['Moving my body'],
    worksForKey: 'Getting outside',
    substanceRelevance: [],
    originOrg: 'Behavioural stimulus-control literature (cue exposure)',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Leave The Room',
    framework: 'Stimulus control — behavioural',
    frameworkNote: 'Cue exposure is the strongest single predictor of use. The cheapest intervention available is distance, applied immediately.',
    why: 'You are standing in the place. No technique out-argues a cue this loud — everything else works better from two hundred metres away. Move first, think second.',
    does: 'Removes the trigger instead of managing it.',
    duration: '3 minutes',
    steps: [
      { t: 20, label: 'Stand up. Now', body: 'Before the next sentence. Coat, phone, door.' },
      { t: 60, label: 'Two hundred metres, any direction', body: 'Uphill if there is an uphill. Count the paces.' },
      { t: 60, label: 'Text one person that you left', body: "Three words is enough. It makes going back a decision you'd have to explain." },
    ],
    tags: {
      mag: ['7–8', '9–10'],
      time: ['Two minutes', 'Five minutes', 'Ten minutes'],
      place: ['Somewhere I used to use', 'Out in public'],
    },
  },
  {
    id: 'ground',
    triggerTags: ['Physical pain', 'Withdrawal'],
    styleTags: ['Sitting with it quietly'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Trauma-informed grounding practice',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: '5–4–3–2–1',
    framework: 'Trauma-informed grounding',
    frameworkNote: 'Sensory orienting. Used to bring attention out of an internal loop and back into the present environment, silently and in public.',
    why: "You're in public and shaking. This one is invisible — nobody standing next to you will know you are doing it, and it works on anxiety faster than it works on craving.",
    does: 'Pulls attention out of your head and into the room.',
    duration: '3 minutes',
    steps: [
      { t: 45, label: 'Five things you can see', body: 'Small and specific. A scuff, a bolt, a price tag.' },
      { t: 40, label: 'Four you can feel', body: 'Fabric at your wrist, floor through your shoes, air on your face.' },
      { t: 35, label: 'Three you can hear', body: 'Nearest, then furthest.' },
      { t: 30, label: 'Two you can smell, one you can taste', body: 'Then breathe out slowly and look up.' },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Two minutes', 'Five minutes'],
      place: ['Out in public', 'At work'],
      emotion: ['Anxiety', 'Shame', 'Fear'],
      body: ['Wired', 'Shaky or sick', 'Nauseous', 'Tense'],
    },
  },
  {
    id: 'delay',
    triggerTags: ['Boredom', 'Wanting a reward', 'Easy money'],
    styleTags: ['Getting distracted on purpose'],
    worksForKey: 'Waiting it out',
    substanceRelevance: [],
    originOrg: 'SMART Recovery (DEADS)',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'The Fifteen-Minute Deal',
    framework: 'SMART Recovery — Deny, Escape, Avoid, Distract, Substitute',
    frameworkNote: 'Deny, Escape, Avoid, Distract, Substitute. You are not promising never; you are promising not yet, for a period short enough to be honest.',
    why: 'You never agreed to quit tonight. You agreed to fifteen minutes, which is a promise you can actually keep, and cravings rarely survive being made to wait with something in your hands.',
    does: "Converts an absolute into a delay you won't have to lie about.",
    duration: '15 minutes',
    steps: [
      { t: 30, label: 'Set fifteen minutes. Say the deal out loud', body: '"Not before this runs out." That\'s the whole contract.' },
      { t: 60, label: 'Put something in your hands', body: 'Food, shower, dishes, cigarette, cold drink. Hands busy, ideally wet or cold.' },
      { t: 90, label: 'When it runs out, re-rate it', body: 'If it dropped, take another fifteen. If it didn\'t, we change instrument.' },
    ],
    tags: {
      mag: ['4–6', '1–3'],
      time: ['Thirty minutes', 'As long as it takes'],
      emotion: ['Boredom', 'Emptiness'],
      body: ['Numb', 'Exhausted', 'In pain'],
    },
  },
  {
    id: 'call',
    triggerTags: ['Loneliness'],
    styleTags: ['Reaching out to someone'],
    worksForKey: 'Calling someone',
    substanceRelevance: [],
    originOrg: 'Peer-support / twelve-step-adjacent social support literature',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'One Call, Script Written',
    framework: 'Social support — twelve-step adjacent',
    frameworkNote: 'The reach-out, stripped of fellowship language. What carries over from AA and NA is only this: the odds change when someone else knows in real time.',
    why: "The reason this fails is never willingness, it's not knowing what to open with — so the opening line is written for you and you only have to press call.",
    does: 'Puts a second person inside the next hour.',
    duration: '5 minutes',
    steps: [
      { t: 20, label: 'Read the line', body: '"It\'s bad tonight and I\'m not asking you to fix it. Just stay on the phone."' },
      { t: 30, label: 'Press call before you edit it', body: 'Editing is how this gets abandoned.' },
      { t: 120, label: 'Say where you are', body: "Location first, feelings second. It's the part that matters if this goes wrong." },
    ],
    tags: {
      mag: ['7–8', '9–10'],
      time: ['Ten minutes', 'Thirty minutes', 'As long as it takes'],
      emotion: ['Shame', 'Grief', 'Emptiness', 'Loneliness'],
      place: ['Home alone', 'Outdoors alone'],
    },
  },
  {
    id: 'night',
    triggerTags: ['Tiredness'],
    styleTags: ['Moving my body'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Behavioural sleep-as-endpoint literature',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Cut The Night Short',
    framework: 'Behavioural — sleep as endpoint',
    frameworkNote: 'Late-night relapse is overwhelmingly a function of hours awake and alone. Ending the day early is a legitimate intervention, not a retreat.',
    why: "You're exhausted with the whole night ahead of you and no reason to still be awake. Nothing good is coming at 2am. Ending the day is a win, not a surrender.",
    does: 'Closes the window rather than defending it.',
    duration: '20 minutes',
    steps: [
      { t: 60, label: 'Phone on the far side of the room', body: 'Charging, screen down, out of arm\'s reach.' },
      { t: 90, label: 'Shower as hot as you can stand', body: 'Then let yourself get cold. The temperature drop is what makes you sleepy.' },
      { t: 120, label: 'Bed, lights off, something spoken', body: "Podcast or audiobook, volume low, timer on. Something you've heard before." },
    ],
    tags: {
      mag: ['1–3', '4–6'],
      time: ['Thirty minutes', 'As long as it takes'],
      body: ['Exhausted', 'Numb'],
      place: ['Home alone', 'Outdoors alone'],
    },
  },
  {
    id: 'stop',
    triggerTags: ['Wanting a reward', 'Easy money', 'Sexual arousal'],
    styleTags: ['Being blunt with myself'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Marsha Linehan / DBT Skills Training Manual',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Stop. Then Decide',
    framework: 'Dialectical Behaviour Therapy — STOP skill',
    frameworkNote:
      'One of DBT\'s four core distress-tolerance skills: Stop, Take a step back, Observe, Proceed mindfully. Built for the exact moment an urge turns into motion.',
    why: 'The urge to act is fastest right when it starts. This doesn\'t try to talk you out of it — it puts four short steps between the impulse and your hands, which is often enough for the next choice to stop being automatic.',
    does: 'Interrupts the impulse-to-action chain before it becomes a decision.',
    duration: '90 seconds',
    steps: [
      { t: 15, label: 'Stop. Freeze exactly where you are', body: "Don't take even a small step toward it yet. Just stop moving toward it." },
      { t: 20, label: 'Take a step back', body: 'Physically or mentally. One breath. Let go of the pressure to react this second.' },
      { t: 30, label: "Observe what's actually happening", body: 'What are you thinking, feeling, and what\'s around you — inside and outside.' },
      { t: 25, label: 'Proceed mindfully', body: 'Ask what response fits what you actually want, not just the urge. Choose one small next action.' },
    ],
    tags: {
      mag: ['7–8', '9–10'],
      time: ['Two minutes'],
      body: ['Wired', 'Heart racing'],
      place: ['Home alone', 'Out in public', 'At work', 'Outdoors alone'],
    },
  },
  {
    id: 'accepts',
    triggerTags: ['Boredom', 'Tiredness'],
    styleTags: ['Getting distracted on purpose'],
    worksForKey: 'Distracting myself on purpose',
    substanceRelevance: [],
    originOrg: 'Marsha Linehan / DBT Skills Training Manual',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'The Distraction List',
    framework: 'Dialectical Behaviour Therapy — ACCEPTS (distraction)',
    frameworkNote:
      'ACCEPTS — Activities, Contributing, Comparisons, Emotions (opposite ones), Pushing away, Thoughts, Sensations. A DBT distress-tolerance skill for urges that are strong but not yet an emergency.',
    why: "When the craving is loud but not a full physiological flood, out-arguing it rarely works — out-occupying it does. This gives your attention somewhere else to go that isn't willpower.",
    does: 'Occupies the same channel the craving is using, on purpose, until the urge loses its grip.',
    duration: '4 minutes',
    steps: [
      { t: 40, label: 'Pick one thing, not five', body: 'Activities, contributing, comparisons, emotions, pushing away, thoughts, sensations — pick one lane and commit to it.' },
      { t: 90, label: 'Do it with your hands or your body', body: 'Clean something, text a friend, watch something that makes you laugh, hold ice, count backward from 100 by 7s.' },
      { t: 110, label: "Keep going until the edge is off", body: "You're not solving anything. You're occupying the part of your brain that's currently running the show." },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Five minutes', 'Ten minutes'],
      emotion: ['Boredom', 'Restlessness'],
      place: ['Home alone', 'Home with other people', 'At work'],
    },
  },
  {
    id: 'soothe',
    triggerTags: ['Boredom', 'Loneliness'],
    styleTags: ['Sitting with it quietly'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Marsha Linehan / DBT Skills Training Manual',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Something For Every Sense',
    framework: 'Dialectical Behaviour Therapy — Self-Soothe',
    frameworkNote:
      "A DBT distress-tolerance skill: deliberately feeding each of the five senses something real, one at a time, instead of leaving the craving as the only thing broadcasting.",
    why: "Numbness and emptiness don't respond well to arguments — they respond to input. This gives every sense something ordinary and real on purpose.",
    does: 'Replaces sensory numbness with deliberate, ordinary sensation.',
    duration: '5 minutes',
    steps: [
      { t: 75, label: 'Sight and sound', body: "Put on something that isn't background noise — actually look at or listen to it. A window, a photo, one song end to end." },
      { t: 75, label: 'Touch and smell', body: 'Something warm or textured in your hands. Coffee, a candle, lotion, fresh air if you can get to it.' },
      { t: 75, label: 'Taste, last', body: "Something you'd actually enjoy, slowly. Not a reward for anything — just proof your senses still work for things that aren't the craving." },
      { t: 75, label: 'Notice what changed', body: "Not gone — just quieter. That's the whole point of this one." },
    ],
    tags: {
      mag: ['4–6'],
      time: ['Five minutes', 'Ten minutes'],
      emotion: ['Emptiness', 'Boredom'],
      body: ['Numb', 'Exhausted'],
      place: ['Home alone', 'Home with other people'],
    },
  },
  {
    id: 'accept',
    triggerTags: ['Physical pain'],
    styleTags: ['Sitting with it quietly'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Marsha Linehan / DBT Skills Training Manual',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: "This Is What's True Right Now",
    framework: 'Dialectical Behaviour Therapy — Radical Acceptance',
    frameworkNote:
      "A DBT distress-tolerance skill for pain that's fused to a fact you can't change tonight. Accepting isn't approving — it's ending the extra fight on top of the fact.",
    why: "Some cravings are fused to a fact you can't change tonight — a loss, a diagnosis, a relationship that's over. Fighting the fact keeps the craving fed. This doesn't ask you to be at peace with it, only to stop spending the fight on the wrong target.",
    does: "Separates the pain that's unavoidable from the extra suffering that comes from refusing what's already true.",
    duration: '6 minutes',
    steps: [
      { t: 60, label: "Say the fact, not the story", body: "Name what's actually true right now, in one plain sentence. Not what it means, not what happens next — just the fact." },
      { t: 90, label: "Notice what you're fighting", body: "Most of what hurts right now is the arguing-with-reality part, not the reality itself. Let the arguing go slack for a minute." },
      { t: 90, label: 'Accept it without agreeing with it', body: "Accepting isn't approving. You can hate that it's true and still stop spending energy pretending it isn't." },
      { t: 120, label: "Ask what's next, given that", body: "Not what you wish were true. Given the actual fact, what's one thing you can do in the next ten minutes?" },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Ten minutes', 'Thirty minutes'],
      emotion: ['Grief', 'Anger', 'Shame'],
    },
  },
  {
    id: 'cba',
    triggerTags: ['Wanting a reward', 'Boredom'],
    styleTags: ['Thinking it through'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'SMART Recovery',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'The Two-Column Truth',
    framework: 'SMART Recovery — Cost-Benefit Analysis',
    frameworkNote:
      "A core SMART Recovery tool: write down what you get and what it costs, side by side, before you decide instead of after. Not a lecture — just the two columns you're currently only looking at one of.",
    why: "Right now you're only running the benefit column in your head — the relief, the quiet, the reward. This makes you write the cost column too, in your own words, before you act instead of at 3am after.",
    does: 'Forces both sides of the decision onto the page at the same time, instead of one side in your head and the other in hindsight.',
    duration: '5 minutes',
    steps: [
      { t: 75, label: 'Short-term benefit, in your own words', body: 'What do you actually get in the next hour if you do this? Be honest, not virtuous. The relief is real.' },
      { t: 90, label: 'Cost, in your own words', body: 'What does it cost you tomorrow, this week, this year? Specific, not vague. Not "it\'s bad for me" — what actually happens.' },
      { t: 135, label: 'Put them side by side', body: "Read both columns out loud, one after the other. You're not choosing yet — you're just finally looking at the whole page." },
    ],
    tags: {
      mag: ['4–6', '7–8'],
      time: ['Five minutes', 'Ten minutes'],
      emotion: ['Anticipation', 'Boredom'],
    },
  },
  {
    id: 'abc',
    triggerTags: ['Anger', 'Hunger'],
    styleTags: ['Thinking it through'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'SMART Recovery (adapted from REBT / Albert Ellis)',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Trace It Back',
    framework: 'SMART Recovery — ABC (Activator, Belief, Consequence)',
    frameworkNote:
      "SMART Recovery's ABC tool, adapted from REBT. The activating event isn't what's driving this — the belief about it is, and that's the part you can actually catch.",
    why: "It feels like the event caused this — but the event happened to everyone in the room and only you are standing here. It's the belief in between that's doing the damage, and beliefs are the one part of this you can actually catch and question.",
    does: 'Separates what happened from what you told yourself it meant, so you can argue with the second one.',
    duration: '6 minutes',
    steps: [
      { t: 60, label: 'Name the activator', body: 'What actually happened, in one plain sentence. Not the meaning — just the event.' },
      { t: 90, label: 'Name the belief', body: 'What did you tell yourself it meant about you? Finish the sentence: "This means I..."' },
      { t: 90, label: 'Name the consequence', body: 'What did that belief make you feel, and what is it telling you to do right now?' },
      { t: 120, label: 'Question the belief, not the event', body: 'Is the belief actually true, or just familiar? What would you tell someone else who said it about themselves?' },
    ],
    tags: {
      emotion: ['Anger', 'Shame', 'Guilt'],
      mag: ['4–6', '7–8'],
      time: ['Ten minutes'],
    },
  },
  {
    id: 'sober',
    triggerTags: ['Tiredness', 'Environment cues'],
    styleTags: ['Sitting with it quietly'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Sarah Bowen / Mindfulness-Based Relapse Prevention',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'The SOBER Space',
    framework: 'Mindfulness-Based Relapse Prevention — SOBER breathing space',
    frameworkNote:
      "Stop, Observe, Breathe, Expand, Respond. MBRP's short-form reset for exactly the moment things start moving too fast to think.",
    why: "You don't have twenty minutes right now and you don't need them — this is the version that fits into a bathroom stall or a parking lot. Five steps, all of them short.",
    does: 'Interrupts the automatic-pilot chain in under three minutes, in a way nobody around you can tell you\'re doing.',
    duration: '3 minutes',
    steps: [
      { t: 20, label: 'Stop', body: "Whatever you're doing, pause it. Don't finish the motion." },
      { t: 25, label: 'Observe', body: "What's happening right now — in your body, your thoughts, around you. Just notice, don't fix." },
      { t: 40, label: 'Breathe', body: 'One breath, all the way down to your stomach. Just the one.' },
      { t: 45, label: 'Expand', body: 'Widen out from the breath to your whole body, then the room you\'re in.' },
      { t: 50, label: 'Respond', body: 'Now choose the next thing on purpose, instead of on autopilot.' },
    ],
    tags: {
      place: ['At work', 'Out in public'],
      mag: ['4–6', '7–8'],
      time: ['Two minutes', 'Five minutes'],
    },
  },
  {
    id: 'scan',
    triggerTags: ['Tiredness', 'Physical pain'],
    styleTags: ['Sitting with it quietly'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Sarah Bowen / Mindfulness-Based Relapse Prevention',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Three Minutes, Head To Toe',
    framework: 'Mindfulness-Based Relapse Prevention — Body Scan',
    frameworkNote:
      "A shortened MBRP body scan. Used when the craving has gone quiet in your head but is still running in your body — numbness, tension, exhaustion that a thought-focused technique won't reach.",
    why: "Some of this isn't in your head right now — it's in your shoulders, your jaw, your stomach. This finds where it's actually sitting instead of arguing with a thought that isn't the real problem.",
    does: "Locates the craving in the body instead of trying to think your way out of something that isn't happening in your thoughts.",
    duration: '4 minutes',
    steps: [
      { t: 60, label: 'Feet and legs', body: "What's actually there — heavy, tense, nothing at all. Don't change it, just find it." },
      { t: 60, label: 'Stomach and chest', body: "This is usually where it's loudest. Notice it without tightening against it." },
      { t: 60, label: 'Shoulders, jaw, hands', body: 'Where you hold things without noticing. Let them be exactly as tense as they are.' },
      { t: 60, label: 'The whole body, at once', body: 'Everything you just found, together. Breathe into the parts that are still loud.' },
    ],
    tags: {
      body: ['Numb', 'Tense', 'Exhausted'],
      place: ['Home alone', 'Home with other people'],
      time: ['Five minutes', 'Ten minutes'],
    },
  },
  {
    id: 'catch',
    triggerTags: ['Anger', 'Loneliness'],
    styleTags: ['Thinking it through'],
    worksForKey: 'Writing it down',
    substanceRelevance: [],
    originOrg: 'Standard CBT thought-record practice',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Catch The Thought',
    framework: 'Cognitive Behavioural Therapy — Thought Record',
    frameworkNote:
      'Standard CBT thought-record work: get the automatic thought onto paper where it can be checked, instead of leaving it running unexamined in your head.',
    why: 'The thought driving this — "I can\'t handle this," "everyone does this," "just this once" — sounds true because it\'s fast and it\'s yours. Slow it down onto paper and it usually loses some of its authority.',
    does: "Turns an automatic thought into something you wrote down and can argue with, instead of something that just happened to you.",
    duration: '5 minutes',
    steps: [
      { t: 45, label: 'Write the thought, word for word', body: "Exactly what's going through your head, not the cleaned-up version." },
      { t: 60, label: 'Write the evidence for it', body: 'What actually supports this being true, right now, specifically.' },
      { t: 60, label: 'Write the evidence against it', body: 'What you know that contradicts it. Be as thorough as you were in the last step.' },
      { t: 135, label: 'Write a truer thought', body: "Not a forced positive one — one that actually fits the evidence better than the first one did." },
    ],
    tags: {
      emotion: ['Shame', 'Guilt', 'Fear'],
      time: ['Five minutes', 'Ten minutes'],
      mag: ['4–6'],
    },
  },
  {
    id: 'ifthen',
    triggerTags: ['Environment cues', 'Easy money'],
    styleTags: ['Being blunt with myself'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Standard CBT practice (implementation intentions)',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'If This, Then That',
    framework: 'Cognitive Behavioural Therapy — Implementation Intentions',
    frameworkNote:
      "Implementation intentions: pre-deciding a specific response to a specific trigger, so the moment it happens doesn't require a fresh decision under pressure.",
    why: "You're standing in the exact situation you're worst at deciding in. This isn't asking you to decide right now — it's asking you to write down the decision so future-you doesn't have to make it from scratch.",
    does: "Replaces an in-the-moment decision with one you already made when you had more room to think.",
    duration: '3 minutes',
    steps: [
      { t: 40, label: 'Name the exact trigger', body: 'Not the general pattern — the specific thing in front of you right now.' },
      { t: 60, label: 'Write the if-then, out loud', body: '"If [this happens], then I will [specific action]." One sentence. Say it like a rule, not a hope.' },
      { t: 80, label: 'Do the "then" part now', body: "Not later. The whole plan is worthless if it waits until you feel like it." },
    ],
    tags: {
      place: ['Out in public', 'At work'],
      time: ['Two minutes', 'Five minutes'],
      mag: ['4–6', '7–8'],
    },
  },
  {
    id: 'defuse',
    triggerTags: ['Wanting a reward', 'Sexual arousal'],
    styleTags: ['Sitting with it quietly'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Acceptance and Commitment Therapy practice',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Just A Thought, Passing By',
    framework: 'Acceptance and Commitment Therapy — Cognitive Defusion',
    frameworkNote:
      'ACT\'s core defusion move: change your relationship to the thought instead of trying to win an argument with it. "I need this" becomes a thing your mind is saying, not an order.',
    why: 'You\'re not going to out-argue "I need this" — it doesn\'t respond to logic because it isn\'t a logical claim, it\'s a craving wearing a sentence. This doesn\'t fight it. It just relabels what it actually is.',
    does: 'Puts distance between you and the thought without requiring you to believe the thought is false.',
    duration: '4 minutes',
    steps: [
      { t: 40, label: 'Name the thought exactly', body: 'Not "I\'m craving" — the actual sentence. "I need this right now" or whatever it\'s saying.' },
      { t: 60, label: 'Add four words in front of it', body: '"I\'m having the thought that..." Say the whole sentence again with those four words stuck on the front.' },
      { t: 60, label: 'Say it in a stupid voice', body: "Cartoon voice, slow motion, whatever. Notice the thought didn't get weaker or stronger — just less like an order." },
      { t: 80, label: "Let it sit there, don't argue", body: "You don't have to make it leave. It can be in the room while you do something else." },
    ],
    tags: {
      emotion: ['Anticipation', 'Anxiety'],
      mag: ['4–6', '7–8'],
      time: ['Five minutes'],
    },
  },
  {
    id: 'values',
    triggerTags: ['Boredom', 'Loneliness'],
    styleTags: ['Thinking it through'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Acceptance and Commitment Therapy practice',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'What This Actually Costs',
    framework: 'Acceptance and Commitment Therapy — Values Clarification',
    frameworkNote:
      "ACT values work: reconnecting with what you actually want your life to be about, as leverage instead of fear. Fear-based reasons wear out fast; this doesn't rely on being scared enough.",
    why: "Willpower fuelled by fear runs out — it's why \"rock bottom\" motivation never lasts on its own. This asks a different question: not what you're scared of, but who you're actually trying to be. That one holds up longer.",
    does: 'Replaces fear as the reason to stop with something that doesn\'t fade after the fear does.',
    duration: '6 minutes',
    steps: [
      { t: 60, label: "Name one person you don't want to let down", body: 'Not the general idea of disappointing people — one actual person.' },
      { t: 90, label: "Name what kind of person you're trying to be", body: "Not the person you're afraid of becoming — the one you're actually aiming at." },
      { t: 90, label: 'Ask if this gets you closer or further', body: 'Not whether it\'s "bad." Whether it moves you toward that person or away from them.' },
      { t: 120, label: 'Pick one thing that moves you toward it', body: 'Something small and doable in the next ten minutes.' },
    ],
    tags: {
      emotion: ['Emptiness', 'Grief'],
      time: ['Ten minutes', 'Thirty minutes'],
      mag: ['4–6'],
    },
  },
  {
    id: 'control',
    triggerTags: ['Anger', 'Physical pain'],
    styleTags: ['Thinking it through'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Stoic philosophy (Epictetus) — informs modern CBT/REBT but not itself a clinical modality',
    evidenceTier: 'emerging',
    reviewStatus: 'drafted',
    name: 'Sort What You Can Actually Move',
    framework: 'Stoic philosophy — Dichotomy of Control',
    frameworkNote:
      "Epictetus's core distinction, stripped of the philosophy lecture: some of this is yours to move, most of it isn't. Energy spent on the second pile is where people get stuck.",
    why: "Most of what's driving this isn't actually in your hands right now — the day, the mood, what already happened. Some tiny piece of it is. This finds that piece and puts everything else down for a minute.",
    does: 'Separates what you can act on from what you\'re just suffering over, so the acting part gets your attention.',
    duration: '4 minutes',
    steps: [
      { t: 60, label: "List what's not yours to move", body: "The event, other people, what already happened, how you feel right now. Say them out loud. None of these are today's job." },
      { t: 60, label: 'Find the one thing that is', body: 'Usually small: the next text, the next step, the next ten minutes. Name it specifically.' },
      { t: 60, label: 'Put the rest down, on purpose', body: 'Not forever — just for the length of this exercise. You can pick the worry back up later if you still want it.' },
      { t: 60, label: 'Do the one small thing', body: "Not think about it — do it. That's the whole exercise." },
    ],
    tags: {
      emotion: ['Anger', 'Fear', 'Anxiety'],
      mag: ['4–6', '7–8'],
      time: ['Five minutes'],
    },
  },
  {
    id: 'meaning',
    triggerTags: ['Boredom', 'Loneliness'],
    styleTags: ['Thinking it through'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Viktor Frankl — Logotherapy',
    evidenceTier: 'emerging',
    reviewStatus: 'drafted',
    name: 'This Moment Has Weight',
    framework: 'Logotherapy (Viktor Frankl) — meaning in the struggle',
    frameworkNote:
      "Frankl's core claim, from his work on meaning-centred psychotherapy: you can't always choose what happens, but you can choose what this moment means to the story you're building. Not a distraction from the craving — a reframe of what resisting it is worth.",
    why: "The craving is telling you this moment doesn't matter, it's just an obstacle to get past. Frankl's whole argument was the opposite: how you handle exactly this kind of moment is where meaning actually gets made, not despite the difficulty but inside it.",
    does: 'Reframes the struggle itself as meaningful instead of as dead time to survive.',
    duration: '4 minutes',
    steps: [
      { t: 50, label: 'Name what this moment is actually testing', body: 'Not in general — specifically, right now, what is this asking of you?' },
      { t: 70, label: 'Name who is affected by how this goes', body: 'Not abstractly. One or two real people, including future-you.' },
      { t: 60, label: 'Say what getting through this would mean', body: 'Not "I\'d feel better." What it would actually say about the kind of person you\'re building.' },
      { t: 60, label: 'Act like this moment matters, because it does', body: 'One action that fits the person you just described.' },
    ],
    tags: {
      emotion: ['Emptiness', 'Grief', 'Boredom'],
      time: ['Five minutes', 'Ten minutes'],
      mag: ['4–6'],
    },
  },
  {
    id: 'identity',
    triggerTags: ['Withdrawal', 'Anger'],
    styleTags: ['Thinking it through'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Jean-Paul Sartre (existentialism) and Alfred North Whitehead (process philosophy) — philosophical framing, not a clinical modality',
    evidenceTier: 'emerging',
    reviewStatus: 'drafted',
    name: 'Not A Sentence, A Sentence In Progress',
    framework: 'Existentialism (Sartre) and Process Philosophy (Whitehead) — identity as ongoing choice',
    frameworkNote:
      "Sartre argued you're defined by what you choose next, not what you've already done. Whitehead's process philosophy makes the same point from a different angle: the self isn't a fixed thing, it's an ongoing event — which means the next moment is still unwritten, always.",
    why: '"I\'m an addict" and "I always do this" feel like facts about who you are. They\'re not — they\'re a description of what you\'ve chosen before, and what you choose next is still open. This isn\'t positive thinking. It\'s just accurate: the sentence isn\'t finished.',
    does: "Separates your identity from your history, so the next choice isn't pre-decided by the last one.",
    duration: '4 minutes',
    steps: [
      { t: 50, label: "Say the label you're using on yourself", body: '"I\'m someone who..." Whatever it is, say the whole sentence.' },
      { t: 60, label: "Notice it's a pattern, not a fact", body: "A pattern is something you've done. A fact is something you can't change. This is the first kind." },
      { t: 70, label: "Say what you're choosing right now instead", body: "Not what you'll always do from now on — just this one choice, right now." },
      { t: 60, label: 'Let that choice be the whole point', body: "It doesn't need to prove anything about tomorrow. It only has to be true for the next ten minutes." },
    ],
    tags: {
      emotion: ['Shame', 'Guilt'],
      mag: ['4–6', '7–8'],
      time: ['Five minutes'],
    },
  },
  {
    id: 'allornothing',
    triggerTags: ['Easy money', 'Wanting a reward'],
    styleTags: ['Thinking it through'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Alan Marlatt — relapse-prevention research on the abstinence violation effect',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: "One Slip Isn't The Whole Story",
    framework: "Relapse-prevention research on the abstinence violation effect, framed through the 'Middle Way'",
    frameworkNote:
      "Named for the Buddhist 'Middle Way' — neither rigid all-or-nothing control nor total indulgence — but the actual mechanism is Alan Marlatt's abstinence violation effect: the belief that one slip means total failure, which is what turns a small lapse into a full relapse.",
    why: '"I already messed up, might as well keep going" is the single most well-documented trap in relapse research. It\'s not really about the craving anymore — it\'s about an all-or-nothing rule you set for yourself that one imperfect moment just broke.',
    does: "Interrupts the jump from 'I slipped' to 'so nothing matters now,' which is a separate decision from the slip itself.",
    duration: '3 minutes',
    steps: [
      { t: 40, label: 'Name the all-or-nothing rule', body: 'What perfect standard did you just believe you broke?' },
      { t: 60, label: "Say what's actually true", body: "One imperfect moment happened. That's the whole fact. It doesn't erase what came before or decide what comes next." },
      { t: 80, label: 'Separate the slip from the spiral', body: "The slip already happened and you can't undo it. The spiral hasn't happened yet — that part is still a choice." },
    ],
    tags: {
      emotion: ['Guilt', 'Shame'],
      time: ['Two minutes', 'Five minutes'],
      mag: ['4–6', '7–8'],
    },
  },
  {
    id: 'habitloop',
    triggerTags: ['Environment cues', 'Boredom'],
    styleTags: ['Being blunt with myself'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'William James (pragmatism) and modern habit-loop behavioural science',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Keep The Cue, Swap The Response',
    framework: 'Behavioural habit-loop science, in the pragmatist tradition of habit as action',
    frameworkNote:
      "William James argued habit is built from repeated action, not belief — pragmatism's basic claim that what you do is what you become. Modern habit research breaks it into cue, routine, reward: you usually can't remove the cue, but you can swap what happens after it.",
    why: "You're not going to delete the cue that just fired — it's already here. What's actually still open is what happens next. Same trigger, same reward you're chasing, different action in between.",
    does: 'Redirects the habit loop instead of trying to fight the cue that already fired.',
    duration: '4 minutes',
    steps: [
      { t: 40, label: 'Name the cue', body: 'What just triggered this, specifically? Not the mood — the actual moment.' },
      { t: 50, label: "Name the reward you're actually chasing", body: 'Relief, escape, a hit of stimulation, quiet. Be specific about what you\'re really after.' },
      { t: 70, label: 'Pick a different action for the same reward', body: "Something that gets you a version of that same reward without the routine you're trying to skip." },
      { t: 80, label: 'Do it now, in place of the old routine', body: 'Not later — right where the old routine would have started.' },
    ],
    tags: {
      place: ['Home alone', 'Out in public', 'At work'],
      time: ['Five minutes', 'Ten minutes'],
      mag: ['4–6'],
    },
  },
  {
    id: 'myth',
    triggerTags: ['Loneliness', 'Withdrawal'],
    styleTags: ['Thinking it through'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: 'Socratic method, applied as in cognitive-behavioural restructuring',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: "Deconstruct The Line You're Telling Yourself",
    framework: 'Socratic method, applied as cognitive restructuring',
    frameworkNote:
      'The Socratic method: instead of accepting a claim, you interrogate it with specific questions until it either holds up or falls apart. Applied here to the specific sentences addiction tells people — not thoughts in general, the actual recurring lines.',
    why: 'There\'s a specific sentence running right now — "I\'ve earned this," "I can stop whenever," "this one doesn\'t count." It sounds like a fact because you\'ve heard it from yourself a hundred times. It hasn\'t earned that. Cross-examine it like you would anyone else\'s claim.',
    does: 'Puts a specific recurring belief on trial instead of accepting it because it\'s familiar.',
    duration: '5 minutes',
    steps: [
      { t: 60, label: 'State the line exactly', body: "Word for word, the sentence that's making this feel reasonable right now." },
      { t: 75, label: 'Ask: is this actually true, or just familiar?', body: 'Familiar and true are not the same thing. Which one is this?' },
      { t: 75, label: 'Ask: what would I tell someone else who said this?', body: "You'd catch it in one second if a friend said it. Say what you'd tell them." },
      { t: 90, label: "Ask what the line is actually for", body: "It exists to make the next ten minutes easier to justify. That's its whole job. Notice that, and set it down." },
    ],
    tags: {
      emotion: ['Loneliness', 'Shame'],
      time: ['Five minutes', 'Ten minutes'],
      mag: ['4–6'],
    },
  },
  {
    id: 'activation',
    triggerTags: ['Boredom', 'Tiredness'],
    styleTags: ['Moving my body'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: "Standard behavioural activation practice; smallest-next-action framing informed by Taoist wu wei",
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Do The Small Thing First',
    framework: 'Behavioural Activation',
    frameworkNote:
      "Standard behavioural activation: waiting to feel motivated before acting has it backwards — action usually comes first, motivation follows. The version here also borrows a line from Taoist practice: the smallest natural next action, done without forcing it.",
    why: "You're waiting to feel like doing something else before you do it. That's backwards — the feeling usually shows up after the action starts, not before. This isn't asking for a plan. It's asking for the smallest possible next physical action.",
    does: 'Starts the behaviour before the motivation arrives, instead of waiting for motivation that isn\'t coming.',
    duration: '3 minutes',
    steps: [
      { t: 30, label: 'Pick the smallest possible action', body: 'Not a project — something that takes under a minute. Stand up. Open a window. Fill a glass.' },
      { t: 40, label: 'Do just that one thing', body: 'Nothing after it yet. Just the one small action.' },
      { t: 60, label: 'Notice what shifted', body: "Probably not much — that's fine. Small is the point, not dramatic." },
      { t: 50, label: 'Pick the next small thing', body: 'Only if you want to. No obligation to keep going.' },
    ],
    tags: {
      emotion: ['Boredom', 'Emptiness'],
      body: ['Numb', 'Exhausted'],
      time: ['Two minutes', 'Five minutes'],
    },
  },
  {
    id: 'pmr',
    triggerTags: ['Physical pain', 'Withdrawal'],
    styleTags: ['Moving my body'],
    worksForKey: 'Tensing and releasing my body',
    substanceRelevance: [],
    originOrg: 'Edmund Jacobson — Progressive Muscle Relaxation',
    evidenceTier: 'established',
    reviewStatus: 'drafted',
    name: 'Tense It, Then Let It Go',
    framework: 'Progressive Muscle Relaxation',
    frameworkNote:
      "Edmund Jacobson's Progressive Muscle Relaxation: deliberately tensing a muscle group before releasing it produces a deeper relaxation than trying to relax directly. Decades of use for anxiety and physical tension.",
    why: 'Telling your body to "just relax" doesn\'t work — it\'s not a switch. This works because you tense on purpose first, so the release afterward is real instead of forced.',
    does: 'Produces actual physical relaxation through contrast, instead of asking a tense body to relax on command.',
    duration: '5 minutes',
    steps: [
      { t: 60, label: 'Hands and arms', body: 'Clench fists tight for five seconds. Let go completely. Feel the difference.' },
      { t: 75, label: 'Shoulders and face', body: 'Scrunch everything up — shoulders to ears, face tight. Hold, then drop it all.' },
      { t: 75, label: 'Stomach and chest', body: 'Tighten your stomach like bracing for a hit. Hold, then let it go soft.' },
      { t: 90, label: 'Legs and feet', body: 'Press feet down, tense your legs. Hold, then let them go heavy.' },
    ],
    tags: {
      body: ['Tense', 'Wired', 'Shaky or sick'],
      place: ['Home alone', 'Home with other people'],
      time: ['Five minutes', 'Ten minutes'],
    },
  },
  {
    id: 'eft',
    triggerTags: ['Wanting a reward', 'Easy money'],
    styleTags: ['Thinking it through'],
    worksForKey: "Picturing how I'd feel later",
    substanceRelevance: [],
    originOrg: 'Episodic future thinking research in addiction and delay-discounting (Bickel, Snider, and related work)',
    evidenceTier: 'emerging',
    reviewStatus: 'drafted',
    name: 'Picture The Actual Morning',
    framework: 'Episodic future thinking (addiction and delay-discounting research)',
    frameworkNote:
      "Research on episodic future thinking finds that vividly imagining a specific, detailed future moment — not a vague one — reduces the pull of an immediate reward. The specificity is what matters; a vague 'better future' doesn't work as well as one exact scene.",
    why: "The craving is only showing you right now. This doesn't argue with it — it just adds a second, equally vivid scene: a specific morning, in detail, that either does or doesn't have this in it.",
    does: 'Makes a specific future moment as vivid as the present one, instead of leaving the future abstract.',
    duration: '4 minutes',
    steps: [
      { t: 50, label: 'Pick one exact future moment', body: 'Not "the future" — one morning, one specific day from now. Name it.' },
      { t: 70, label: 'Fill in the real details', body: "Where are you, what do you see, who's there, what does the air feel like. Make it specific, not aspirational." },
      { t: 60, label: "Put today's decision inside that scene", body: "Does tonight belong in that morning, or not? Not good or bad — does it fit the scene you just built?" },
      { t: 60, label: 'Hold both scenes side by side', body: 'Right now, and that morning. You get to pick which one this moment belongs to.' },
    ],
    tags: {
      emotion: ['Anticipation', 'Guilt'],
      time: ['Five minutes', 'Ten minutes'],
      mag: ['4–6'],
    },
  },
  {
    id: 'turnover',
    triggerTags: ['Withdrawal', 'Physical pain'],
    styleTags: ['Reaching out to someone'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: "Secularized adaptation of twelve-step 'turning it over'",
    evidenceTier: 'emerging',
    reviewStatus: 'drafted',
    name: 'Hand This One Off',
    framework: "Secularized adaptation of the twelve-step 'turning it over'",
    frameworkNote:
      "Adapted from twelve-step practice, stripped of religious language. The underlying move isn't supernatural — it's a real psychological shift: admitting this particular moment is bigger than raw willpower alone, and redirecting effort into reaching out instead of white-knuckling it. This specific secular rewrite hasn't itself been studied — the tradition it's adapted from has a real, if imperfect, evidence base.",
    why: "You've been trying to win this one alone, on willpower, and it isn't holding. That's not a character failure — some moments are bigger than one person gritting their teeth. This is about redirecting the effort, not giving up: from \"fight it alone\" to \"get this moment some help.\"",
    does: 'Redirects effort from solo willpower toward reaching for support, without requiring any belief system to do it.',
    duration: '3 minutes',
    steps: [
      { t: 40, label: 'Admit this one is bigger than willpower alone', body: 'Not weakness — just true, for tonight, right now.' },
      { t: 60, label: 'Name what "handing it off" looks like tonight', body: 'A call, a message, an instrument, stepping outside. Something outside your own head.' },
      { t: 80, label: 'Do that one thing', body: 'Not think about doing it. The whole exercise is the handoff itself.' },
    ],
    tags: {
      emotion: ['Shame', 'Grief', 'Emptiness'],
      time: ['Two minutes', 'Five minutes'],
      mag: ['7–8', '9–10'],
    },
  },
  {
    id: 'toughlove',
    triggerTags: ['Boredom', 'Easy money'],
    styleTags: ['Being blunt with myself'],
    worksForKey: null,
    substanceRelevance: [],
    originOrg: "Directive coaching style, precedented in SMART Recovery's confrontational tradition and behavioural activation's 'act first' principle",
    evidenceTier: 'emerging',
    reviewStatus: 'drafted',
    name: 'Stop Negotiating With Yourself',
    framework: 'Directive coaching style — action-forcing, not a clinical modality',
    frameworkNote:
      'Not therapy, not a diagnosis-specific technique — a blunter register than the rest of this library, closer to SMART Recovery\'s confrontational tradition and behavioural activation\'s "act before you feel like it" principle. For the profile that explicitly asked to skip the gentler stuff.',
    why: 'You\'ve been negotiating with yourself for the last few minutes, and every round of that negotiation is time spent moving closer, not further. This isn\'t going to ask how you feel about it. Stop arguing with yourself and do the next line.',
    does: 'Cuts the internal negotiation short instead of validating it.',
    duration: '2 minutes',
    steps: [
      { t: 30, label: 'Stop the negotiation', body: 'No more "just this once" or "one more argument for it." The debate is over. You already know the answer.' },
      { t: 40, label: "Say what you're actually doing instead, out loud", body: 'One sentence. Not a feeling — an action.' },
      { t: 50, label: 'Do it. Now.', body: "Not after this exercise. Immediately. That's the whole point of this one." },
    ],
    tags: {
      mag: ['7–8', '9–10'],
      time: ['Two minutes'],
      emotion: ['Anticipation'],
    },
  },
];

export const RULE_BLOCK = {
  'Talking to a person': ['call'],
  'Outdoor or sport activities': ['leave'],
  'Anything over ten minutes': ['delay', 'night', 'surf'],
  'Philosophy or wisdom-tradition framing': ['control', 'meaning', 'identity', 'habitloop', 'myth', 'turnover'],
  'Religious or spirituality talk': ['turnover'],
  'Tough love': ['toughlove'],
};

export const HARM_ITEMS = [
  { label: "For opioids: make sure naloxone is at arm's length", sub: 'Not in a drawer. Not in a bag. Within sight.' },
  { label: 'Ensure someone is nearby and you are in reach of help', sub: 'Most overdoses are survivable with a witness.' },
  { label: 'Take nothing on top of it', sub: 'No benzos, no alcohol, no second thing.' },
  { label: 'Test it, then take a quarter first', sub: 'Tolerance is gone after a break. Wait ten minutes.' },
  { label: 'Stay hydrated and put something in your stomach', sub: "If it's alcohol: one glass of water between each." },
  { label: 'Make sure one person knows where you are', sub: "Give them the actual address, not just 'out tonight'." },
];
